"""Materials Project field table — GENERATED, do not edit by hand.

Regenerate with: python tools/gen_mp_vocab.py  (source: 0.87.2.dev4+g6bd8ed856)

MP_FIELDS maps each retrievable SummaryDoc property to its pinned unit (None =
dimensionless/count), XC-functional origin (None = no traceable functional),
schema description (None = the schema ships no gloss; a curated override fills the
load-bearing blanks), and rankable (False = a boolean flag — a hard filter, never
a ranking target). PUSHABLE_PARAMS is the /summary GET query-param surface — the
names the adapter is allowed to push server-side (distinct from, and larger than,
MP_FIELDS).
"""

MP_FIELDS: dict[str, dict] = {
    "band_gap": {"unit": "eV", "origin": "electronic_structure", "desc": "Band gap energy in eV.", "rankable": True},
    "bulk_modulus": {"unit": "GPa", "origin": None, "desc": "Voigt, Reuss, and Voigt-Reuss-Hill averages of the bulk modulus in GPa.", "rankable": True},
    "cbm": {"unit": "eV", "origin": "electronic_structure", "desc": "Conduction band minimum data.", "rankable": True},
    "density": {"unit": "g/cm³", "origin": "structure", "desc": "Density in g/cm³.", "rankable": True},
    "density_atomic": {"unit": "Å³/atom", "origin": "structure", "desc": "The atomic packing density in Å³/atom.", "rankable": True},
    "dos_energy_down": {"unit": "eV", "origin": "electronic_structure", "desc": "Spin-down DOS band gap in eV.", "rankable": True},
    "dos_energy_up": {"unit": "eV", "origin": "electronic_structure", "desc": "Spin-up DOS band gap in eV.", "rankable": True},
    "e_electronic": {"unit": None, "origin": "dielectric", "desc": "Electronic contribution to dielectric constant.", "rankable": True},
    "e_ij_max": {"unit": "C/m²", "origin": "piezoelectric", "desc": "Piezoelectric modulus.", "rankable": True},
    "e_ionic": {"unit": None, "origin": "dielectric", "desc": "Ionic contribution to dielectric constant.", "rankable": True},
    "e_total": {"unit": None, "origin": "dielectric", "desc": "Total dielectric constant.", "rankable": True},
    "efermi": {"unit": "eV", "origin": "electronic_structure", "desc": "Fermi energy in eV.", "rankable": True},
    "energy_above_hull": {"unit": "eV/atom", "origin": "energy", "desc": "The energy above the hull in eV/Atom.", "rankable": True},
    "energy_per_atom": {"unit": "eV/atom", "origin": "energy", "desc": "The total corrected DFT energy of this material per atom in eV/atom.", "rankable": True},
    "equilibrium_reaction_energy_per_atom": {"unit": "eV/atom", "origin": "energy", "desc": "The reaction energy of a stable entry from the neighboring equilibrium stable materials in eV. Also known as the inverse distance to hull.", "rankable": True},
    "formation_energy_per_atom": {"unit": "eV/atom", "origin": "energy", "desc": "The formation energy per atom in eV/atom.", "rankable": True},
    "homogeneous_poisson": {"unit": None, "origin": None, "desc": "Poisson's ratio.", "rankable": True},
    "is_gap_direct": {"unit": None, "origin": "electronic_structure", "desc": "Whether the band gap is direct.", "rankable": False},
    "is_magnetic": {"unit": None, "origin": "magnetism", "desc": "Whether the material is magnetic.", "rankable": False},
    "is_metal": {"unit": None, "origin": "electronic_structure", "desc": "Whether the material is a metal.", "rankable": False},
    "is_stable": {"unit": None, "origin": "energy", "desc": "Flag for whether this material is on the hull and therefore stable.", "rankable": False},
    "n": {"unit": None, "origin": "dielectric", "desc": "Refractive index.", "rankable": True},
    "nelements": {"unit": None, "origin": None, "desc": "Number of elements.", "rankable": True},
    "nsites": {"unit": None, "origin": "structure", "desc": "Total number of sites in the structure.", "rankable": True},
    "num_magnetic_sites": {"unit": None, "origin": "magnetism", "desc": "The number of magnetic sites.", "rankable": True},
    "num_unique_magnetic_sites": {"unit": None, "origin": "magnetism", "desc": "The number of unique magnetic sites.", "rankable": True},
    "shape_factor": {"unit": None, "origin": None, "desc": "Shape factor.", "rankable": True},
    "shear_modulus": {"unit": "GPa", "origin": None, "desc": "Voigt, Reuss, and Voigt-Reuss-Hill averages of the shear modulus in GPa.", "rankable": True},
    "surface_anisotropy": {"unit": None, "origin": None, "desc": "Surface energy anisotropy.", "rankable": True},
    "total_magnetization": {"unit": "μB", "origin": "magnetism", "desc": "Total magnetization in μB.", "rankable": True},
    "total_magnetization_normalized_formula_units": {"unit": "μB/f.u.", "origin": "magnetism", "desc": "Total magnetization normalized by formula unit in μB/f.u. .", "rankable": True},
    "total_magnetization_normalized_vol": {"unit": "μB/Å³", "origin": "magnetism", "desc": "Total magnetization normalized by volume in μB/Å³.", "rankable": True},
    "uncorrected_energy_per_atom": {"unit": "eV/atom", "origin": "energy", "desc": "The total DFT energy of this material per atom in eV/atom.", "rankable": True},
    "universal_anisotropy": {"unit": None, "origin": None, "desc": "Elastic anisotropy.", "rankable": True},
    "vbm": {"unit": "eV", "origin": "electronic_structure", "desc": "Valence band maximum data.", "rankable": True},
    "volume": {"unit": "Å³", "origin": "structure", "desc": "Total volume for this structure in Å³.", "rankable": True},
    "weighted_surface_energy": {"unit": "J/m²", "origin": None, "desc": "Weighted surface energy in J/m².", "rankable": True},
    "weighted_surface_energy_EV_PER_ANG2": {"unit": "eV/Å²", "origin": None, "desc": "Weighted surface energy in eV/Å².", "rankable": True},
    "weighted_work_function": {"unit": "eV", "origin": None, "desc": "Weighted work function in eV.", "rankable": True},
}

PUSHABLE_PARAMS: frozenset[str] = frozenset(
    {
        "_all_fields",
        "_fields",
        "_limit",
        "_page",
        "_per_page",
        "_skip",
        "_sort_fields",
        "band_gap_max",
        "band_gap_min",
        "batch_id",
        "batch_id_eq_any",
        "batch_id_neq_any",
        "batch_id_not_eq",
        "cbm_max",
        "cbm_min",
        "chemsys",
        "crystal_system",
        "density_atomic_max",
        "density_atomic_min",
        "density_max",
        "density_min",
        "deprecated",
        "dos_energy_down_max",
        "dos_energy_down_min",
        "dos_energy_up_max",
        "dos_energy_up_min",
        "e_electronic_max",
        "e_electronic_min",
        "e_ij_max_max",
        "e_ij_max_min",
        "e_ionic_max",
        "e_ionic_min",
        "e_total_max",
        "e_total_min",
        "efermi_max",
        "efermi_min",
        "elements",
        "energy_above_hull_max",
        "energy_above_hull_min",
        "energy_per_atom_max",
        "energy_per_atom_min",
        "equilibrium_reaction_energy_per_atom_max",
        "equilibrium_reaction_energy_per_atom_min",
        "exclude_elements",
        "formation_energy_per_atom_max",
        "formation_energy_per_atom_min",
        "formula",
        "g_reuss_max",
        "g_reuss_min",
        "g_voigt_max",
        "g_voigt_min",
        "g_vrh_max",
        "g_vrh_min",
        "has_props",
        "has_reconstructed",
        "homogeneous_poisson_max",
        "homogeneous_poisson_min",
        "id_format",
        "is_gap_direct",
        "is_metal",
        "is_stable",
        "k_reuss_max",
        "k_reuss_min",
        "k_voigt_max",
        "k_voigt_min",
        "k_vrh_max",
        "k_vrh_min",
        "license",
        "material_ids",
        "n_max",
        "n_min",
        "nelements",
        "nelements_eq_any",
        "nelements_max",
        "nelements_min",
        "nelements_neq_any",
        "nelements_not_eq",
        "nsites",
        "nsites_eq_any",
        "nsites_max",
        "nsites_min",
        "nsites_neq_any",
        "nsites_not_eq",
        "num_magnetic_sites",
        "num_magnetic_sites_eq_any",
        "num_magnetic_sites_max",
        "num_magnetic_sites_min",
        "num_magnetic_sites_neq_any",
        "num_magnetic_sites_not_eq",
        "num_unique_magnetic_sites",
        "num_unique_magnetic_sites_eq_any",
        "num_unique_magnetic_sites_max",
        "num_unique_magnetic_sites_min",
        "num_unique_magnetic_sites_neq_any",
        "num_unique_magnetic_sites_not_eq",
        "ordering",
        "possible_species",
        "shape_factor_max",
        "shape_factor_min",
        "spacegroup_number",
        "spacegroup_symbol",
        "surface_anisotropy_max",
        "surface_anisotropy_min",
        "theoretical",
        "total_magnetization_max",
        "total_magnetization_min",
        "total_magnetization_normalized_formula_units_max",
        "total_magnetization_normalized_formula_units_min",
        "total_magnetization_normalized_vol_max",
        "total_magnetization_normalized_vol_min",
        "uncorrected_energy_per_atom_max",
        "uncorrected_energy_per_atom_min",
        "universal_anisotropy_max",
        "universal_anisotropy_min",
        "vbm_max",
        "vbm_min",
        "volume_max",
        "volume_min",
        "weighted_surface_energy_EV_PER_ANG2_max",
        "weighted_surface_energy_EV_PER_ANG2_min",
        "weighted_surface_energy_max",
        "weighted_surface_energy_min",
        "weighted_work_function_max",
        "weighted_work_function_min",
    }
)
