"""Materials Project field table — GENERATED, do not edit by hand.

Regenerate with: python tools/gen_mp_vocab.py  (source: 0.87.2.dev4+g6bd8ed856)

MP_FIELDS maps each retrievable SummaryDoc property to its pinned unit (None =
dimensionless/count) and XC-functional origin (None = no traceable functional).
PUSHABLE_PARAMS is the /summary GET query-param surface — the names the adapter
is allowed to push server-side (distinct from, and larger than, MP_FIELDS).
"""

MP_FIELDS: dict[str, dict] = {
    "band_gap": {"unit": "eV", "origin": "electronic_structure"},
    "bulk_modulus": {"unit": "GPa", "origin": None},
    "cbm": {"unit": "eV", "origin": "electronic_structure"},
    "density": {"unit": "g/cm³", "origin": "structure"},
    "density_atomic": {"unit": "Å³/atom", "origin": "structure"},
    "dos_energy_down": {"unit": "eV", "origin": "electronic_structure"},
    "dos_energy_up": {"unit": "eV", "origin": "electronic_structure"},
    "e_electronic": {"unit": None, "origin": "dielectric"},
    "e_ij_max": {"unit": "C/m²", "origin": "piezoelectric"},
    "e_ionic": {"unit": None, "origin": "dielectric"},
    "e_total": {"unit": None, "origin": "dielectric"},
    "efermi": {"unit": "eV", "origin": "electronic_structure"},
    "energy_above_hull": {"unit": "eV/atom", "origin": "energy"},
    "energy_per_atom": {"unit": "eV/atom", "origin": "energy"},
    "equilibrium_reaction_energy_per_atom": {"unit": "eV/atom", "origin": "energy"},
    "formation_energy_per_atom": {"unit": "eV/atom", "origin": "energy"},
    "homogeneous_poisson": {"unit": None, "origin": None},
    "is_gap_direct": {"unit": None, "origin": "electronic_structure"},
    "is_magnetic": {"unit": None, "origin": "magnetism"},
    "is_metal": {"unit": None, "origin": "electronic_structure"},
    "is_stable": {"unit": None, "origin": "energy"},
    "n": {"unit": None, "origin": "dielectric"},
    "nelements": {"unit": None, "origin": None},
    "nsites": {"unit": None, "origin": "structure"},
    "num_magnetic_sites": {"unit": None, "origin": "magnetism"},
    "num_unique_magnetic_sites": {"unit": None, "origin": "magnetism"},
    "shape_factor": {"unit": None, "origin": None},
    "shear_modulus": {"unit": "GPa", "origin": None},
    "surface_anisotropy": {"unit": None, "origin": None},
    "total_magnetization": {"unit": "μB", "origin": "magnetism"},
    "total_magnetization_normalized_formula_units": {"unit": "μB/f.u.", "origin": "magnetism"},
    "total_magnetization_normalized_vol": {"unit": "μB/Å³", "origin": "magnetism"},
    "uncorrected_energy_per_atom": {"unit": "eV/atom", "origin": "energy"},
    "universal_anisotropy": {"unit": None, "origin": None},
    "vbm": {"unit": "eV", "origin": "electronic_structure"},
    "volume": {"unit": "Å³", "origin": "structure"},
    "weighted_surface_energy": {"unit": "J/m²", "origin": None},
    "weighted_surface_energy_EV_PER_ANG2": {"unit": "eV/Å²", "origin": None},
    "weighted_work_function": {"unit": "eV", "origin": None},
}

PUSHABLE_PARAMS: frozenset[str] = frozenset(
    {
        "_all_fields",
        "_fields",
        "_limit",
        "_page",
        "_per_page",
        "_skip",
        "_sort_fields",
        "band_gap_max",
        "band_gap_min",
        "batch_id",
        "batch_id_eq_any",
        "batch_id_neq_any",
        "batch_id_not_eq",
        "cbm_max",
        "cbm_min",
        "chemsys",
        "crystal_system",
        "density_atomic_max",
        "density_atomic_min",
        "density_max",
        "density_min",
        "deprecated",
        "dos_energy_down_max",
        "dos_energy_down_min",
        "dos_energy_up_max",
        "dos_energy_up_min",
        "e_electronic_max",
        "e_electronic_min",
        "e_ij_max_max",
        "e_ij_max_min",
        "e_ionic_max",
        "e_ionic_min",
        "e_total_max",
        "e_total_min",
        "efermi_max",
        "efermi_min",
        "elements",
        "energy_above_hull_max",
        "energy_above_hull_min",
        "energy_per_atom_max",
        "energy_per_atom_min",
        "equilibrium_reaction_energy_per_atom_max",
        "equilibrium_reaction_energy_per_atom_min",
        "exclude_elements",
        "formation_energy_per_atom_max",
        "formation_energy_per_atom_min",
        "formula",
        "g_reuss_max",
        "g_reuss_min",
        "g_voigt_max",
        "g_voigt_min",
        "g_vrh_max",
        "g_vrh_min",
        "has_props",
        "has_reconstructed",
        "homogeneous_poisson_max",
        "homogeneous_poisson_min",
        "id_format",
        "is_gap_direct",
        "is_metal",
        "is_stable",
        "k_reuss_max",
        "k_reuss_min",
        "k_voigt_max",
        "k_voigt_min",
        "k_vrh_max",
        "k_vrh_min",
        "license",
        "material_ids",
        "n_max",
        "n_min",
        "nelements",
        "nelements_eq_any",
        "nelements_max",
        "nelements_min",
        "nelements_neq_any",
        "nelements_not_eq",
        "nsites",
        "nsites_eq_any",
        "nsites_max",
        "nsites_min",
        "nsites_neq_any",
        "nsites_not_eq",
        "num_magnetic_sites",
        "num_magnetic_sites_eq_any",
        "num_magnetic_sites_max",
        "num_magnetic_sites_min",
        "num_magnetic_sites_neq_any",
        "num_magnetic_sites_not_eq",
        "num_unique_magnetic_sites",
        "num_unique_magnetic_sites_eq_any",
        "num_unique_magnetic_sites_max",
        "num_unique_magnetic_sites_min",
        "num_unique_magnetic_sites_neq_any",
        "num_unique_magnetic_sites_not_eq",
        "ordering",
        "possible_species",
        "shape_factor_max",
        "shape_factor_min",
        "spacegroup_number",
        "spacegroup_symbol",
        "surface_anisotropy_max",
        "surface_anisotropy_min",
        "theoretical",
        "total_magnetization_max",
        "total_magnetization_min",
        "total_magnetization_normalized_formula_units_max",
        "total_magnetization_normalized_formula_units_min",
        "total_magnetization_normalized_vol_max",
        "total_magnetization_normalized_vol_min",
        "uncorrected_energy_per_atom_max",
        "uncorrected_energy_per_atom_min",
        "universal_anisotropy_max",
        "universal_anisotropy_min",
        "vbm_max",
        "vbm_min",
        "volume_max",
        "volume_min",
        "weighted_surface_energy_EV_PER_ANG2_max",
        "weighted_surface_energy_EV_PER_ANG2_min",
        "weighted_surface_energy_max",
        "weighted_surface_energy_min",
        "weighted_work_function_max",
        "weighted_work_function_min",
    }
)
